# Generated by Django 6.1.1 on 2026-10-06 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.ManyToManyField(related_name='categories', to='tasks.categories')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='devs.developer')),
            ],
        ),
    ]
